<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="/styles.css" rel="stylesheet"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tenor+Sans&display=swap" rel="stylesheet">
</head>
<body>
<header class="header">
    <div class="header-content">
        <div class="header-logo">
            <a href="/"><img class="header-logo" src="./images/Header logo.svg" alt="logo">
            </a>
        </div>
        <nav class="main-nav">
            <ul class="nav-list">
                <li class="nav-item"><a href="/practise">Практика</a></li>
                <li class="nav-item"><a href="/library">Библиотека</a></li>
                <li class="nav-item"><a href="/study">Учебные материалы</a></li>
            </ul>
        </nav>
        <div class="login-button-container">
            <button class="buttonLgn-popup">
                Войти
            </button>
        </div>
    </div>
</header>
<h1>Практика</h1>
</body>
</html>